# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fastapi-arima-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ac825f9d279b4aac9eb301197c18921c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ca9d98d13fe944de846ec920c534e24a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ac825f9d279b4aac9eb301197c18921c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-arima-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_407321504cef42c180a0477a5a4c7baf }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ac825f9d279b4aac9eb301197c18921c }}/appsvc/staticsite:${{ github.sha }}'